CXX = g++
CPPFLAGS = -Wall -g -fPIC
INCLUDES = \
	-I/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers \
	-I/Users/ekeller/C_Stuffs/boost_1_57_0
SRCS = NativeBitSet.cc
OBJS = $(SRCS:.cc=.o)
MAIN = nativeoss

.PHONY: depend clean

all: $(MAIN)

$(MAIN): $(OBJS)
	$(CXX) -shared  $(CPPFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS)

.cc.o:
	$(CXX) $(CPPFLAGS) $(INCLUDES) -c $< -o $@

clean:
	$(RM) *.o *~ $(MAIN)

depend: $(SRCS)
	makedepend $(INCLUDES) $^

# DO NOT DELETE THIS LINE -- make depend needs it

NativeBitSet.o: NativeBitSet.h
NativeBitSet.o: /System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h
NativeBitSet.o: /usr/include/stdio.h /usr/include/sys/cdefs.h
NativeBitSet.o: /usr/include/sys/_symbol_aliasing.h
NativeBitSet.o: /usr/include/sys/_posix_availability.h
NativeBitSet.o: /usr/include/Availability.h
NativeBitSet.o: /usr/include/AvailabilityInternal.h /usr/include/_types.h
NativeBitSet.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
NativeBitSet.o: /usr/include/i386/_types.h
NativeBitSet.o: /usr/include/sys/_pthread/_pthread_types.h
NativeBitSet.o: /usr/include/sys/_types/_va_list.h
NativeBitSet.o: /usr/include/sys/_types/_size_t.h
NativeBitSet.o: /usr/include/sys/_types/_null.h /usr/include/sys/stdio.h
NativeBitSet.o: /usr/include/sys/_types/_off_t.h
NativeBitSet.o: /usr/include/sys/_types/_ssize_t.h
NativeBitSet.o: /usr/include/secure/_stdio.h /usr/include/secure/_common.h
NativeBitSet.o: /System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni_md.h
