/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jaeksoft_searchlib_util_array_NativeIntBufferedArray */

#ifndef _Included_com_jaeksoft_searchlib_util_array_NativeIntBufferedArray
#define _Included_com_jaeksoft_searchlib_util_array_NativeIntBufferedArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jaeksoft_searchlib_util_array_NativeIntBufferedArray
 * Method:    init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jaeksoft_searchlib_util_array_NativeIntBufferedArray_init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jaeksoft_searchlib_util_array_NativeIntBufferedArray
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jaeksoft_searchlib_util_array_NativeIntBufferedArray_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jaeksoft_searchlib_util_array_NativeIntBufferedArray
 * Method:    add
 * Signature: (J[II)V
 */
JNIEXPORT void JNICALL Java_com_jaeksoft_searchlib_util_array_NativeIntBufferedArray_add
  (JNIEnv *, jobject, jlong, jintArray, jint);

/*
 * Class:     com_jaeksoft_searchlib_util_array_NativeIntBufferedArray
 * Method:    getSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jaeksoft_searchlib_util_array_NativeIntBufferedArray_getSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jaeksoft_searchlib_util_array_NativeIntBufferedArray
 * Method:    populateFinalArray
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_com_jaeksoft_searchlib_util_array_NativeIntBufferedArray_populateFinalArray
  (JNIEnv *, jobject, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
