#!/bin/sh

if which invoke-rc.d >/dev/null 2>&1; then
	invoke-rc.d tomcat6 stop
else
	/etc/init.d/tomcat6 stop
fi

rm /var/lib/tomcat6/webapps/opensearchserver.war
rm -r /var/lib/tomcat6/webapps/opensearchserver
